apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  annotations:
    "": ""
  labels:
    "": ""
  name: test1
  namespace: test1-clutch-dev1
spec:
  bootstrap:
    recovery:
      database: test-database
  enableSuperuserAccess: true
  instances: 3
  monitoring:
    customQueriesConfigMap:
    - key: test
      name: test-upgrade
    - key: test2
      name: "123"
    customQueriesSecret:
    - key: quetry
      name: query-test
  storage:
    size: 1Gi
  walStorage:
    size: 11Gi
