apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  annotations:
    "": ""
  labels:
    "": ""
  name: test-migrate
  namespace: test1-clutch-dev1
spec:
  enableSuperuserAccess: true
  instances: 3
  storage:
    size: 1Gi
