apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: qa1-rbac-editor
  namespace: test1-clutch-qa1
rules:
  - apiGroups:
      - "*"
    resources:
      - "*"
    verbs:
      - create
      - delete
      - update
      - get
      - list
      - watch
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: oidc-qa1-rbac-editor
  namespace: test1-clutch-qa1
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: qa1-rbac-editor
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: CPaaS-stage-test1-editor
